server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4FhpV8mLDfhih29KdHLG # 自己的accessKeyId
    accessKeySecret: Kzv3JHnRLF8Eo9JGSnSSIpiCNn3SIA # 自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_185232305 # 模板名称